name: mlflow-tutorial
dependencies:
  - python=3.7
  - numpy
  - pandas
  - jupyter 
  - scikit-learn
  - matplotlib
  - pip:
    - mlflow 
    - torch===1.3.1
    - torchvision===0.4.2 -f https://download.pytorch.org/whl/torch_stable.html